apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wm-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wm-auth-db-dep
  labels:
    app: wm-auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wm-auth-db
  template:
    metadata:
      labels:
        app: wm-auth-db
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: wm-auth-pvc
      containers:
        - name: wm-auth-db-container
          image: mongo:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: storage
              mountPath: /data/db
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: wm-auth-db-svc
spec:
  selector:
    app: wm-auth-db
  ports:
    - port: 27017
      targetPort: 27017
